More attempts to catch really bad errors.
This one is when the website is down, the api call http connect times out,
I get a $res that is ="Can't connect to panel.cloudatcost.com:443"

There is still a bug, because the upper layers die wierdly:

    0$ ./test_api --credfile credfile.txt  listservers --debug --cacheflush
    > GET https://panel.cloudatcost.com/api/v1/listservers.php?<removed>
    < 500 Can't connect to panel.cloudatcost.com:443
    error: bad: Can't connect to panel.cloudatcost.com:443

    Connection timed out at /usr/share/p0$